version: ""

formatter: markdown table

name: terraform-aws-multiaccount-pipeline

content: |-
  # Terraform Multiaccount Pipeline

  This module assumes an aws config recorder is already configured for the account.

  Links to AWS Provided Conformance Packs
  - https://github.com/awslabs/aws-config-rules/tree/master/aws-config-conformance-packs

  --- 

  ## Example with Git Source

  ```hcl
  {{ include "examples/main.tf" }}
  ```

  ---

  {{ .Requirements }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  ---

  Note, manual changes to the README will be overwritten when the documentation is updated. To update the documentation, run `terraform-docs -c .config/.terraform-docs.yml .`

sections:
  show:
    - requirements
    - resources
    - inputs
    - outputs

sort:
  enabled: true
  by: name

output:
  file: README.md
  mode: replace